services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: bwamicro_api_gateway
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - bwamicro

networks:
  bwamicro:
    external: true
